linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  misspell:
    ignore-words:
    - creater

linters:
  enable:
  - errorlint
  - exportloopref
  - gofmt
  - importas
  - misspell
  - nilerr
