apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  identity: null
  latestResourceSchemas:
  - v220628-546034da.clusterworkspaces.tenancy.kcp.dev
  - v220628-546034da.workspaces.tenancy.kcp.dev
  - v220701-d1a091f0.clusterworkspacetypes.tenancy.kcp.dev
status: {}
