apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: tenancy.kcp.dev
spec:
  latestResourceSchemas:
  - v220711-1fe32801.clusterworkspaces.tenancy.kcp.dev
  - v220711-1fe32801.workspaces.tenancy.kcp.dev
  - v220711-e9c8ae2c.clusterworkspacetypes.tenancy.kcp.dev
  maximalPermissionPolicy:
    local: {}
status: {}
