apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: kubernetes
spec:
  latestResourceSchemas:
  - v124.ingresses.networking.k8s.io
  - v124.services.core
  - v124.deployments.apps
  maximalPermissionPolicy:
    local: {}
status: {}
