apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: organization
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Universal
    path: root
  limitAllowedChildren:
    types:
    - name: Team
      path: root
    - name: Universal
      path: root
  limitAllowedParents:
    types:
    - name: Root
      path: root
