apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homeroot
spec:
  initializer: true
  allowedChildren:
    types:
      - path: root
        name: Homebucket
  allowedParents:
    types:
    - path: root
      name: Root
  
