apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kcp:authenticated:users-clusterworkspace-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kcp:users-clusterworkspace-access
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
