apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: team
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: universal
    path: root
  limitAllowedParents:
    types:
    - name: organization
      path: root
