apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homebucket
spec:
  initializer: true
  allowedChildWorkspaceTypes:
  - Homebucket
  - Home
  allowedParentWorkspaceTypes:
  - Homebucket
  - Homeroot
  
