apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homeroot
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Homebucket
    path: root
  limitAllowedChildren:
    types:
    - name: Homebucket
      path: root
  limitAllowedParents:
    types:
    - name: Root
      path: root
