apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:kcp:users-clusterworkspace-access
rules:
- apiGroups: ["tenancy.kcp.dev"]
  resources: ["clusterworkspaces/content"]
  resourceNames: ["users"]
  verbs: ["access"]
