apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: home
spec:
  extend:
    with:
    - name: universal
      path: root
  defaultChildWorkspaceType:
    name: universal
    path: root
  limitAllowedParents:
    types:
    - name: homebucket
      path: root
