apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: root
spec:
  defaultChildWorkspaceType:
    name: organization
    path: root
  parentConstraints:
    none: true
  extend:
    with:
    - name: universal
      path: root
