apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homeroot
spec:
  initializer: true
  allowedChildWorkspaceTypes:
  - Homebucket
  allowedParentWorkspaceTypes:
  - Root
  
