apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: home
spec:
  initializer: true
  defaultChildWorkspaceType:
    path: root
    name: Universal
  allowedParents:
    types:
    - path: root
      name: Homebucket
