apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: team
spec:
  initializers:
  - tenancy.kcp.dev/team
  defaultChildWorkspaceType: Universal
  allowedChildWorkspaceTypes:
    - Any
  allowedParentWorkspaceTypes:
    - Organization
