apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: team
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Universal
    path: root
  allowAnyChildWorkspaceTypes: true
  allowedParentWorkspaceTypes:
    - name: Organization
      path: root
