apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: organization
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Universal
    path: root
  allowedChildWorkspaceTypes:
  - name: Team
    path: root
  - name: Universal
    path: root
  allowedParentWorkspaceTypes:
  - name: Root
    path: root
