apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: universal
spec:
  initializer: true
  additionalWorkspaceLabels:
    workloads.kcp.dev/schedulable: "true"
  defaultChildWorkspaceType: Universal
  allowedChildWorkspaceTypes:
  - Any
  allowedParentWorkspaceTypes:
  - Any
