apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homebucket
spec:
  initializer: true
  allowedChildren:
    types:
    - path: root
      name: Homebucket
    - path: root
      name: Home
  allowedParents:
    types:
    - path: root
      name: Homebucket
    - path: root
      name: Homeroot
  
