apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: homebucket
spec:
  initializer: true
  defaultChildWorkspaceType:
    name: Home
    path: root
  limitAllowedChildren:
    types:
    - name: Homebucket
      path: root
    - name: Home
      path: root
  limitAllowedParents:
    types:
    - name: Homebucket
      path: root
    - name: Homeroot
      path: root
