name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16

    # Check gofmt and lint, but proceed if they fail (we'll fail later).
    - name: Check gofmt
      continue-on-error: true
      run: |
        gofmt -s -d \
          $(find . \
            -path './vendor' -prune \
            -o -type f -name '*.go' -print)
    - uses: golangci/golangci-lint-action@v2
      continue-on-error: true

    # Build and test.
    - run: make build
    - run: go test -race ./...

    # If gofmt or lint checks failed, fail the job.
    - if: ${{ failure() }}
      run: echo "A previous step failed"; exit 1
