name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  gofmt:
    name: gofmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16
    - name: Check gofmt
      run: |
        gofmt -s -d \
          $(find . \
            -path './vendor' -prune \
            -o -type f -name '*.go' -print)
    - name: Check imports
      run: |
        make imports
        if  ! git diff --exit-code; then
          echo "imports are out of date, run make imports"
          exit 1
        fi

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16
    - uses: golangci/golangci-lint-action@v2
      with:
        only-new-issues: true
        args: --timeout=5m

  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: reviewdog/action-misspell@v1
      with:
        exclude: ./.github/workflows/*  

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16

    - run: make build
    - run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...
