name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16

    # Check gofmt, but proceed if gofmt failed (fail later).
    - name: Check gofmt
      continue-on-error: true
      run: |
        gofmt -s -d \
          $(find . \
            -path './vendor' -prune \
            -o -type f -name '*.go' -print)

    - run: make build

    # If gofmt check failed but build didn't, fail the job.
    - if: ${{ failure() }}
      run: echo "A previous step failed"; exit 1
