name: Demos

on:
  workflow_dispatch:

jobs:
  build-and-run-demos:
    name: Build and Run Demos
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: v1.16

    - run: make build
    
    - uses: engineerd/setup-kind@v0.5.0
      name: Install Kind
      with:
        skipClusterCreation: true
        version: v0.10.0

    - name: Prepare Demo tests
      run:
        sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&
        sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 &&
        sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 &&
        sudo apt-get install pv

    - name: Test Demos
      run: mkdir tests && cd tests && ../contrib/demo/runDemos.sh -t
      
    - name: Archive Demo test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: demo-tests
        path: tests/**/*.log
